# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb745cdfa6a0bca4ed1a9f2e698600fe8adb54ffeee80af8ba098ac97ac59aa740f454aec4cdb9abc1b8d7ff931c6ffda70aa42686996616868614b3c09d8f02

test:
  secret_key_base: 1893b3b369185852706bef869f88f8267c6e387b6c71d3b3dd4a099df9074f337ef4a58467f6e79989f1fedca93b030a593dbe19aa09c9401b4158b1ba7cdff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
